### ISSUE TITLE
Help: Hide inserting row after data insert

### ISSUE THREAD

**Issue by abhimishra18** [tabalinas/jsgrid#1038]
Hi Need help for following two scenario
1. I want to hide my inserting row after data gets inserted.
if I am doing $("#jsGrid").data("JSGrid").option("inserting", false);  its hiding the inserting row but not toggling the header row insert icon (+) to previous state.
2. Disable insert row (+) icon once max row count in grid reaches certain number and re enable it once any record gets deleted.

Thanks in advance

**Comment by tabalinas** [comment]
You need some tweaking of the `control` field.

1. click the button instead of hiding the inserting row manually: `$(".jsgrid-insert-mode-button").click()`

2. handle `onRefreshed` event (http://js-grid.com/docs/#onrefreshed) and disable `.jsgrid-insert-mode-button` depending on the amount of items in the grid
