### ISSUE TITLE
Smart filtering based on calculation

### ISSUE THREAD

**Issue by powermic** [tabalinas/jsgrid#1043]
Hi,

Help Request/Question:

I'm trying to figure out how to filter values (type: number) by one of the calculation like:
>5
<-10
=15
>=-25
<=6.5

Is there any way now to do it?

P.S.: if I appended "%" to each value how do I remove it before filtering assuming that I don't enter % in the filter field.

**Comment by tabalinas** [comment]
define `filterTemplate` for your filed. It can contain say a textbox and a dropdown with compare operation. Then define `filterValue` which will return filter representation say `{ operation: '<', target: '-10' }`. Since filtering should be implemented, read use this filter representation on client or server side to filter out the data.
