### ISSUE TITLE
Help Request/Question: Keep sort when searching

### ISSUE THREAD

**Issue by Bene-Graham** [tabalinas/jsgrid#1047]
Is there a way to keep the current sorting when filtering?

I have been digging through the documentation but have not found a way to keep the currently sorted column after a user searches.

Now I know I could apply a sort after OnDataLoaded if the getSorting() comes back with nothing. But this would end up with an additional call back to the server and would not be the exact column the user selected to sort.

Regards,

**Comment by tabalinas** [comment]
`search` method resets sorting, `loadData` doesn't. `search` method is the one used in the `control` field. To use `loadData` method instead, you can override `_createSearchButton` method of the control field, so that it calls `loadData` instead https://github.com/tabalinas/jsgrid/blob/master/src/fields/jsgrid.field.control.js#L170
