### ISSUE TITLE
How can I use bootstrap select

### ISSUE THREAD

**Issue by StarkovArt** [tabalinas/jsgrid#1064]
Hi, how can I use bootstrap-select in js-grid ... without setTimeout and document.ready(), where I can initialize bootstrap select
https://silviomoreto.github.io/bootstrap-select/

Now, I use like this ... but it's bad approach 

 setTimeout(function() {
     $result.selectpicker({
          container: "body",
         noneSelectedText: ""
    });

**Comment by tabalinas** [comment]
The problem is the element should be attached to the body, for the component to be initialized.
That's why we need this async initialization. Do you have any specific issue with using `setTimeout`?
As an alternative you could use `onRefreshed` callback (http://js-grid.com/docs/#onrefreshed), but in this case you would need to select all divs for component and then init your widgets.
