### ISSUE TITLE
Radio Button as column

### ISSUE THREAD

**Issue by mehroz377** [tabalinas/jsgrid#1074]
I need to add a field into the grid that selects a particular row using radio button then get the selected row like a checkbox, is it possible?

**Comment by tabalinas** [comment]
Yes, you will need to create a custom field for this radio button (an example of a custom field in docs http://js-grid.com/docs/#custom-field). The selection logic should be implemented. Add a click handler for this radio button field so that it saves currently selected row. `rowClass` (http://js-grid.com/docs/#rowclass) can add a css class to the selected rows.

**Comment by tabalinas** [comment]
Feel free to come back with concrete questions.
