### ISSUE TITLE
"Text" field doesn't have html escaping

### ISSUE THREAD

**Issue by StefH** [tabalinas/jsgrid#132]
When the data defined in the data array or via remote data contains html text, this text is directly rendered which could lead to strange behavior if the database contains data like 
```html
<script>alert('hi');</script>
```

Would it be an idea to add a new property to the text field like **escapeHTML** which is default set to true?

Example code to escape:
```js
var map = { '&': '&amp;',
            '<': '&lt;',
            '>': '&gt;',
            '"': '&quot;',
            "'": '&#39;'};

function escapeHTML (s, forAttribute) {
    return s.replace(forAttribute ? /[&<>'"]/g : /[&<>]/g, function(c) {
        return map[c];
    });
}
```

Or does this change break the edit-functionality?

**Comment by tabalinas** [comment]
Good point. The problem is current developer has full control over the cell content. He can escape content on backend side or on validation step (before saving to DB). If we'll build-in functionality in the grid, it is too strict (moreover it's Breaking Change). If we put this into the field's code, then we lose escaping once user set custom itemTemplate. I would postpone this issue for now (maybe for next major version)
