### ISSUE TITLE
Edit Row does not maintain alignment.

### ISSUE THREAD

**Issue by danielson317** [tabalinas/jsgrid#178]
CSS styles bug.

When values are set to not editable they become center aligned during an edit operation instead of maintaining the alignment set by the field type. It's unavoidable for the form items to be left aligned but non-editable fields should maintain alignment.

Example: https://www.evernote.com/l/AlgFDoiOxg1HNIbs0NRHF_A7TIZRH6KSaOE

**Comment by tabalinas** [comment]
I see the issue, but have no idea how it could be improved. 
Currently, all fields in edit row are aligned at the center. This makes inputs/selects nicely centered.
If we will provide the align from the data cell to edit cell, inputs/selects will be aligned not at center (possible right or left). This won't look good. Moreover it's a breaking change, which will break the appearance after jsgrid update. So the problem is: no way to distinguish an edit cell with input inside and just a plain text.
Do you have any idea how it could be fixed?
