### ISSUE TITLE
select field issue with String ID

### ISSUE THREAD

**Issue by geemang2000** [tabalinas/jsgrid#2]
I'm having an issue with using a String for the valueField in a select. When I select a new item from the select the cell goes blank. 

        $("#jsGrid").jsGrid({
            editing: true,
            data: db.apps,
    	    fields: [
	    {name: "source", title:"Source", type: "select", items: db.sources, valueField: "Id", textField: "Name"}
	    ...
	    db.sources = [
	        { Name: "Label1", Id: "LABEL1" },
	        { Name: "Label2", Id: "LABEL2" }
	    ];

See:  http://jsbin.com/repexoyuqi/  (click a row, change the select value, click the first button on the control cell)

**Comment by tabalinas** [comment]
Yes, current SelectField implementation inherits NumberField and parses selected value to number. Of course, it should work for strings too.
For now there is a workaround. 
Redefine `editValue` (`filterValue` and `insertValue` if filtering and inserting is needed) to avoid parsing.
(link to field config http://js-grid.com/docs/#fields)

````javascript
{ name: "source", title:"Source", type: "select", 
  items: db.sources, valueField: "Id", textField: "Name"
  editValue : function() { return this.editControl.val(); }, // for editing
  filterValue : function() { return this.filterControl.val(); }, // for filter
  insertValue : function() { return this.insertControl.val(); } // for insert
} 
````

You also could define new field to avoid grid config cluttering. Just register a new field inheriting from jsGrid.SelectField with following code:

````javascript
function TextSelectField(config) {
    jsGrid.SelectField.call(this, config);
}

TextSelectField.prototype = new jsGrid.SelectField({
    
    sorter: "string",
    
    filterValue: function() {
        return this.filterControl.val();
    },

    insertValue: function() {
        return this.insertControl.val();
    },

    editValue: function() {
        return this.editControl.val();
    }
});

jsGrid.fields.textSelect = TextSelectField;
````

Now you can use this field just like before, but specify `type="textSelect"`instead of `type="select"`

**Comment by arnvidhr** [comment]
I've tried 1st variant, without creating the new type, so after editing displayed text disappearing.

P.S. How you can do id as numeric? You never know, what type id is. Might be GUID, what is mandatory for MSSQL database with replication enabled, might be completely something else. During more than 2 decades of DB development I seen large variety of ID types. Some serious accounting systems even using varchars of 20-30 symbols length. That's why I always using string type for id, what never fails and never trying to convert it to something else, or to analyze. 

In long run it saves a lot of time. Eg. in begin designed system with ints later can change id type to something else, when you have them as string, you never in trouble...
