### ISSUE TITLE
Have problem with headerRowRenderer and control field

### ISSUE THREAD

**Issue by phyllis0618** [tabalinas/jsgrid#204]
See the code here:
http://jsfiddle.net/72j3ht5c/

I find out if using the headerRowRenderer, the control field which can insert or search will split into two row. How to add the headerRow with control field, I find in the example http://jsfiddle.net/RedScorp/3e1vvhvb/1/, they do not have the search and insert row. Wondering how to do the multiheader with control row.

Thanks

**Comment by tabalinas** [comment]
First, you can turn on filtering row setting the option `filtering:true` (the same for `inserting: true`).
Since `headerRowRenderer` is defined all header rendering is on the shoulders of the developer.
So you can add a `<th>` with `rowspan=2`, and render there the `headerTemplate` of control field.
See your fiddle updated http://jsfiddle.net/tabalinas/3e1vvhvb/4/
