### ISSUE TITLE
issue when checkbox query is set to false

### ISSUE THREAD

**Issue by rstormsf** [tabalinas/jsgrid#21]
If you have boolean value which we show by `checkbox` type, then we want to search by all false values, the query isn't set. It only works to query by true values.

**Comment by tabalinas** [comment]
Checkbox field supports intermediate state. So filter value has 3 possible values: `true | false | undefined`
Since filtering is user responsibility and can be implemented on client or on server sides, it depends on you filtering implementation.

This how it's implemented in jsGrid demos on the client side for Married checkbox field:

````javascript
loadData: function(filter) {
    return $.grep(this.clients, function(client) {
        return (!filter.Name || client.Name.indexOf(filter.Name) > -1)
            && (filter.Married === undefined || client.Married === filter.Married);
    });
},
````

For the server side, e.g. you could pass to the server 0 instead of `undefined` (intermediate state) and `1/-1` for `true/false`.

**Comment by rstormsf** [comment]
my bad I had this one in my code:
```
var searchQ = _.pick(filter, _.identity);
```
