### ISSUE TITLE
style

### ISSUE THREAD

**Issue by ashhorner** [tabalinas/jsgrid#230]
This is a question, not an issue, apologies  but I couldn't see a way of marking it as such.

How do I get the grid to style as per the examples?  I am using the styles listed in the getting started section of the jsGrid website but they don't pull through:

My code is as follows:

`<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/cupertino/jquery-ui.css">
    <link rel="stylesheet" href="https://ssl.gstatic.com/docs/script/css/add-ons1.css">
    
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.4.1/jsgrid.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.4.1/jsgrid-theme.min.css" />
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script> 
        
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.4.1/jsgrid.min.js"></script>
`

**Comment by tabalinas** [comment]
What kind of styling issues do you have? The grid is not styled at all or maybe you have some particular styling issues?
You can put a screenshot in comments.

**Comment by ashhorner** [comment]
The grid is not styled...I guess that makes sense...I was hoping that I could implement the same styling as the demos.

**Comment by tabalinas** [comment]
No, it doesn't. Because, as I noted, there could be 2 different issues with styling:
 - no styling at all (there could issues with wrong links to jsgrid css)
 - or particular differences between styling you get and the grid styling in the demo.

Since grid bases it's styling on the document font it influences on the overall styling (even on the size).
In this case DevTools of Chrome can help to take styles of the demo.

Here is what we have for the demo page as a font:

```css
body {
    font-family: 'Helvetica Neue Light', 'Open Sans', Helvetica;
    font-size: 14px;
    font-weight: 300;
}
```
