### ISSUE TITLE
Callback for custom Field when rendered

### ISSUE THREAD

**Issue by ko-vasilev** [tabalinas/jsgrid#247]
So basically what I want to do is to add a bootstrap tooltip for a text field and it requires to call methods on elements that are attached to DOM.
I know that I can listen to onRefreshed on the grid level, but it would be much better to do it on the custom field level (so I don't have to remember to re-initialize tooltips for all tables where I use this custom field).

Thanks.

**Comment by tabalinas** [comment]
Please, checkout this issue https://github.com/tabalinas/jsgrid/issues/72
I guess `setTimeout` should do the trick.

**Comment by ko-vasilev** [comment]
Thank you for the suggestion, I'll use it for now.
IMO it would be good to have some kind of callback available for these cases.

**Comment by tabalinas** [comment]
Yes, it sounds reasonable. The problem is: currently data appended by rows (not cells) so it's easy to add a callback for rendered row, but then I don't see big difference between using onRowRendered and onRefreshed. Introducing a callback for cells requires some artificial firing of callbacks, when a row is rendered, and this may cause performance issues for large grids. Let's keep it like this for now and see maybe at some point we'll introduce it in the future.

**Comment by buckelieg** [comment]
Sadly to see this issue is closed.
This would be nice feature to have.
On the other hand I would propose to modify _itemTrmplate_ method by providing renderContext parameter if it is possible on that stage.
Having crutches within onRefreshed method to finish rendering custom field is awful - it brakes grid architecture :(
