### ISSUE TITLE
Is there a quick way to disable input into the grid?

### ISSUE THREAD

**Issue by soongsta** [tabalinas/jsgrid#256]
Hi There

Is there a quick way to disable input into the grid?
Currently I am setting 
editing:false,
inserting:false,
deleting:false,

It would be great to just set 1 properties or call 1 method

Cheers

**Comment by tabalinas** [comment]
There is no property `deleting` for the field, since it's impossible to delete just single field.
About the rest it depends on what you mean by disabling a field. 
If don't specify field `type` option, you will get a readonly field. 
If it's not what you are looking for, provide more details about your use case.

**Comment by soongsta** [comment]
The context is user permissions. Some users only have read permission and so  I wanted a readony or disabled jsGrid. I can make it work as described above. Thanks
