### ISSUE TITLE
Would you consider a big patch file / pull request?

### ISSUE THREAD

**Issue by velis74** [tabalinas/jsgrid#263]
During my work with jsGrid (currently based off of 1.3), I have modified it to support the following features (order by position in code :p ):

- clik on row (anywhere) immediately triggers editing
- grid "deleting" propery (same as inserting / updating)
- some jqueryUI theming compatibility (header row, icons are jqueryUI "rendered")
- inserting & editing reacts to ENTER (commit) and ESC (discard)
- custom failCallback for _controllerCall (internal): allows for some special processing when needed
- marking errors in the fields when AJAX returns error state (json must contain {field_name: [list of error strings], field_name: ... })
- fix for item parameter in .editItem() event handler
- added rowById function (though I need to fix this sometime for jsGrid to actually KNOW IDs)
- updateItem can take addtitional parameter preventing call of the controller (the controller was called elsewhere)
- added "prefix" parameter for fields - allows to prefix field value with a constant (good for fields that are e.g. numeric, but they need a description)
- fix for field values: when null or undefined, an empty string is printed, not "null" or "undefined"
- NumberField takes additional "min" and "max" parameters which are then passed to the input control
- TextAreaField by default creates a textarea with max-height and overflow (they were getting really big when stuffed with 100K of text :)
- ControlField modifications: editButton, deleteButton toggles, jqueryUI icons, insert button calls onInsert handler
- onInsert, onDelete, onEdit handlers which are triggered before grid goes into the appropriate mode (allows for custom operations, such as dialogs, etc.)
- custom fields: Select2Field, SelectmenuField, DateField (also introduces a nice Date.format function), CustomField (calls handlers for each value so each row can have a differend control)

I'm sure I forgot something, but let's say this is the gist of it. Most of the changes are not invasive to your existing code, except the jqueryUI functionality - I wasn't thorough with it so I had to leave your CSS in function which required me to remove your classes. If theming rework were complete, it would mostly be a matter of plugging-in different element classes.

My immeditate plan is to make the grid WAY more powerful with AJAX:

- tackle the insane performance issues when 1000s of rows are in the grid (refresh is called way too often)
- deferred record loading in seamless mode (only load the record when it comes into view)
- other fixes & modifications to make this the grid my customer demand :D 

Ok, so why this post:
I would like to contribute back, but until now I was a bit lax in doing that, so I have this huge changeset which is definitely awkward for a pull request, especially since I have seen you released 1.4 in the mean time and I think it also supports onInsert, onDelete, onEdit events (which would definitely conflick with my implementation)

This is the last opportunity for me to try merge my code with yours before I just fork away forever because the changeset would become too big & difficult to merge with trunk every time.

So, if you're interesed in my modifications or plans, how can we make this work together?

**Comment by tabalinas** [comment]
First of all thank you for your efforts and sharing all these modifications. Doing a single PR with multiple changes is not the right way. Each change should be done in a separate PR.

Regarding changes themselves it's hard to say, because it's not always clear what stands behind it:

1. clik on row (anywhere) immediately triggers editing
Not clear what it means. The default behavior is to start editing row on click, and it can be customized with `rowClick` handler.

2. grid "deleting" propery (same as inserting / updating)
What does it mean? How can a field can be deleted and the rest part of the row will stay untouched?

3. some jqueryUI theming compatibility (header row, icons are jqueryUI "rendered")
Not sure about necessity of compatibility with jQueryUI. The component is not a jQueryUI widget, it's just based on jQuery. Thus in the roadmap there is a bootstrap theme and currently I'm working on integration with Angular. So grid should not be that jQueryUI compatible in sense of theming.

4. inserting & editing reacts to ENTER (commit) and ESC (discard)
Keyboard support is a very good feature. It will go right after Angular integration.
But of course it's share your progress on that

5. custom failCallback for _controllerCall (internal): allows for some special processing when needed
What is meant by "special processing needs"? Do you have cases that cannot be handled by existing callbacks and controller methods?

6. marking errors in the fields when AJAX returns error state (json must contain {field_name: [list of error strings], field_name: ... })
Sounds as a little bit adhoc scenario. jsgrid currently supports validation, can it be used in this case?

7. fix for item parameter in .editItem() event handler
What issue is meant here?

8. added rowById function (though I need to fix this sometime for jsGrid to actually KNOW IDs)
`Id` here stands for what? Is it DOM element id? Or data item id?
Not sure about the use case of the method.

9. updateItem can take addtitional parameter preventing call of the controller (the controller was called elsewhere)
Why `onItemEditing` and `onItemUpdating` argument `e.cancel` cannot do the job?

10. added "prefix" parameter for fields - allows to prefix field value with a constant (good for fields that are e.g. numeric, but they need a description)
Why not just redefine `itemTemplate`? It should be fairly easy, like: `itemTemplate: function(value) { return "prefix " + value; }`. Do you think it makes sense to introduce yet another property for this?

11. fix for field values: when null or undefined, an empty string is printed, not "null" or "undefined"
Tried quickly with the latest sources and cannot reproduce the bug.
It would be good to know the details, and of course share the fix.

12. NumberField takes additional "min" and "max" parameters which are then passed to the input control
I believe now we can use validation for this.

13. TextAreaField by default creates a textarea with max-height and overflow (they were getting really big when stuffed with 100K of text :)
Have you put it in css? Currently there is a minimum styling for content to avoid styles clashing. You never know what will be put inside the cell, so content styling is usually up to developer. But if this is a bug, them it worth the PR. 

14. ControlField modifications: editButton, deleteButton toggles, jqueryUI icons, insert button calls onInsert handler
What does `editButton` and `deleteButton` toggles stand for?

15. onInsert, onDelete, onEdit handlers which are triggered before grid goes into the appropriate mode (allows for custom operations, such as dialogs, etc.)
Why we cannot use `onItemInserting`, `onItemDeleting`, and `onItemEditing` for this?

16. custom fields: Select2Field, SelectmenuField, DateField (also introduces a nice Date.format function), CustomField (calls handlers for each value so each row can have a differend control)
Additional fields depending on other components cannot be ship with the grid due to new dependencies. But it would be good to share their code and put somewhere in the docs. It's also in the roadmap to create a page with additional fields for different cases on http://js-grid.com.

- Regarding performance issue, maybe you could open an issue with an example (in fiddle or anyhow).
- Virtual scrolling is also an accepted enhancement, but not for the nearest future.

I believe it's always better to go with the latest version of component to be able to use the latest features and improve the widget itself. We can merge things that make sense and add a value to the component.

**Comment by velis74** [comment]
"Each change should be its own PR": I know, that's why I asked. 

1. The default behaviour did not work for me, so I had to resolve the row item before actually calling editItem()
2. **grid** "deleting", not **field** "deleting". Setting this option to false disables the deleting button from control field and prevends deleting in deleteItem()
3. "Not sure about necessity of compatibility with jQueryUI": Well, it seems at least I found it necessary. I'm not saying it should only support jqueryUI theming, only that it should eventually support a plugin that would enable that. I'm not all that profficient with JavaScript, so I don't know how to implement that. However, if you force Bootstrap on me, I will be unable to use that version. Theming should be a plugin, no matter which framework. I just hoped for something I seem to cannot get when I mentioned this.
4. I don't know what you mean by your answer here. Would a PR be welcome or not?
5. change no. 6 is the "special processing" meant here
6. Processing results returned from server doesn't seem an "ad hoc" scenario to me. Client-side validation is fine, but it's the server that always has the final say.
7. Well, the *item* parameter to handler was the row, not the data item. The fix fixes this.
8. In this case it's data item id. This however **IS** an ad-hoc solution (presumes there's an "id" member in item)
9. The event handlers are not the way to go in this case because I want to set a row item from elsewhere. The handlers are called as a result and don't know the cause of being called. Like I said: this parameter handles a scenario when the item data was obtained via a different AJAX call (page section with the entire item fieldset where grid only shows a small subset).
10. Your suggestion for this one is much better. One learns something each day :)
11. Don't know how you can't reproduce, Currently field itemTemplate returns *value* as it is. If it is null or undefined, that will be printed as text verbatim.
12. Maybe so, I have not yet seen validation as my current base is 1.3
13. No, this was not a bug. I't a matter of preference. I just didn't like rows being **that** high
14. editButton, deleteButton booleans when set to false prevent their respective buttons from being created (because their respective actions are being triggered elsewhere).
15. The handlers you mention are called much later in the process - when the entry is actually completed and the user wants to store the data. These handlers are called before the insertRow / editRow are even constructed and before the delete question is asked.
16. Agreed, they might be part of optional plugins or something. I do believe though that it would be nice if they were provided somehow to prevent users from reinventing the wheel every time.

- about the performance issue: add 100000 rows and call `render`. I have a i2600K@4.6 GHz and it takes a noticeable time. Multiply this by 10 grids I have on the page and you get an unresponsive page. Literally!
- Sorry to hear you feel virtual scrolling such an unworthy feature.

I agree that latest code should always be used. However I don't have time to constantly check for new versions of every library. I sync every now and then. This entire question is based on the fact that I just checked and noticed that we both do a lot of development on the grid - each for his own reasons. Those reasons sometimes overlap, mostly they don't. Additionally, regarding some features I definitely need your help with as my expertise is too lacking (jqueryUI theming, change no. 10, for example).

OTOH I need to have some way of maintaining changes which you won't accept as pull requests. The end result should always be an accepted pul request or a possibility to achieve the same thing via a plugin, hopefully not by adding one line to a copied 30-line function. If we reach an agreement here it will mean a more work for me to split all this into 16 pull requests. I'm willing to do it if you're willing to spend some time dealing with my pull requests.

**Comment by tabalinas** [comment]
Ok, then we need to see what is worth a PR and what can be done just with the current implementation.
Here is some conclusions, feel free to correct me if disagree:

1. if default didn't work for, it can be easily redefined - no PR
2. deletion can be turned off in `control` field it self (`deleteButton: false`) - no PR
3. "Theming should be a plugin, no matter which framework." - completely agree, that's why don't see the point to go for jQueryUI, but maybe I just should see that changes you are talking about - need more details
4. Basic keyboard support - PR
5. no PR
6. There is a plan in the nearest future to support deferred (async) validation, so it won't be client-side only. For the server one, I don't want to put strick format rules here, any implementation and format can be done and handled on the `done` of controller method calls and handled accordingly. Or you see any limitations? - need more details
7. Not sure that I understand: `editItem` accepts both an item or a row - need more details
8. no PR
9. parameters can be passed in many ways: in the data item, put in the grid instance, read from outside object, but if you can do a PR we could see what it mean exactly - PR
11. cannot reproduce with the latest sources, so for now - no PR (unless you can reproduce)
13. can be easily done with outer css - no PR
14. `editButton` and `deleteButton` are options in `control` field - no PR
15. `onItemEditing` is fired before edit row is created, so issue is solved. For the showing inserting row `onOptionChanging` callback can be handled for the option `inserting` - no PR
16. Yes, so please, share the code of these fields - no PR
17. Performance issue - not sure that any changes can make the work with 100 000 grid fast (I'm not talking about virtual scrolling here). It's just browsers limitations, that's why we need tricks like partial items rendering and so on. Or you think it's a particular bottleneck in the jsGrid implementation? For me it's an antipattern to put so many data to client, and `pageLoading: true` for the rescue.
18. No, I don't say that it's not important, but there are just some stuff that have higher priority (angular integration, keyboard support in particular).

Thank you again for your efforts in making js-grid better.

**Comment by velis74** [comment]
I estimate that we have some major conceptual differences which will mean a bunch of my PRs getting rejected. That is especially because I know some of my solutions have been only to solve the immediate problem, not present a general solution that would work for every corner case. I can't decide nor guess which ones are worth spending time on and which are not and that makes it very likely that I will be spending hours on a PR, trying to improve the solution, which you will then simply reject. 

I have concluded that it is much less work and the same amount of control if I just attach my current version here and you can use a diff tool to merge what is interesting to you. That is what I do when I want to merge with YOUR latest release and it takes ~15 minutes. That vs estimated > 6 hours needed to prepare all the PRs makes a clear winner in my eyes. You decide for yourself.

[The ZIP](https://github.com/velis74/dictdiff/blob/master/jsgrid.ZIP) with combined jsgrid & custom fields.

**Comment by tabalinas** [comment]
Thanks for sharing you sources. I'll take a look at diff.
