### ISSUE TITLE
Problem with filter

### ISSUE THREAD

**Issue by ElioRiba** [tabalinas/jsgrid#274]
Hi,
 I found i little bit problem when I use a field with type:"number" like this:

`
{ name: "StockNumber", type: "number", width: 50, align: "left", css: "customfamilyfont", align:"center" }
`
when I load data from grid the filter for this column return 0 (zero) and my DB query doesn't work because expects "" (null).
here my php db request:

`
$sql = "SELECT * FROM InboundUk WHERE StockNumber LIKE '$stock'";
`

I might solve this problem changing type:"number" into type:"text", but I think it is not a great choice.

May I use another system to solve this?

**Comment by tabalinas** [comment]
This is current behavior of `number` field. Maybe it makes sense to default to `null` instead of `0`, but would be a breaking change. 
For current implementation I see two options:
1) handle this in the SQL query `$stock = 0 OR StockNumber LIKE $stock` (in your case it will cause weird side-effect if user will put `'0'`, but I guess this case is not that usual - filtering numeric field as string)
2) or just redefining accordingly to return `null`. 
This is current implementation `filterValue: function() { return parseInt(this.filterControl.val(), 10); }`
Return `null` if `this.filterControl.val()` is an empty string.

**Comment by ElioRiba** [comment]
Hi,
 I tried to use the second way, but it returns NaN, so it doesn't work because the filter expects "".
Consider my DB field is INT (or Float) and into gsgrid is "numeric".

**Comment by tabalinas** [comment]
Could you provide your code of `filterValue`?

**Comment by ElioRiba** [comment]
Of Course!
Here we go.
`
{ name: "StockNumber", type: "number", width: 50, align: "left", css: "customfamilyfont", align:"center",
                     filterValue: function() { return parseInt(this.filterControl.val(), 10); }
                    }
`

**Comment by tabalinas** [comment]
Ok, but you just used current implementation, as I wrote

> Return null if this.filterControl.val() is an empty string.

So it should be something like:

```js
filterValue: function() { 
    var value = this.filterControl.val();
    return value === "" ? null : parseInt(value, 10); 
}
```

**Comment by ElioRiba** [comment]
Perfect,
 thanks a lot it works well!
Regards
