### ISSUE TITLE
sorting & filtering not working in loading by page

### ISSUE THREAD

**Issue by shandy05** [tabalinas/jsgrid#30]
why sorting & filtering not working in loading by page?
any solution?

**Comment by tabalinas** [comment]
**Filtering** should be always implemented by developer. It may be implemented whether on client or server side. On client side we put filtering logic into controller method `loadData`. On the server side (more common) we pass filter parameters to the server script and apply filtering on server side to avoid transferring of unnecessary data to the client. Thus there is no difference between loading by page and direct loading in case of filtering.

**Sorting** is really differ for direct loading and loading by page. Direct loading sorts data of the grid. Loading by page strategy just reloads data providing paging parameters to the `filter` argument of controller `loadData` method (`pageIndex` current page index and `pageSize` - current page size from grid config). Why it happens this way: loading by page makes sense only when you implement all filtering and sorting logic on the server side, when you have big amount of data. Just imagine you've loaded only first page, does it really make sense to sort only this first page items? Sorting of all data can be implemented only on the server side, because grid just don't have other data.

**Possible solution**
Anyway, if you wish sorting of data on the current page, it's doable. 
All the difference in behavior between  loading by page and direct loading is extracted to loadingStrategies (didn't have time yet to describe this advanced info in docs).

```javascript
    jsGrid.loadStrategies = {
        DirectLoadingStrategy: DirectLoadingStrategy,
        PageLoadingStrategy: PageLoadingStrategy
    };
```

The direct loading strategy does following on sorting:

```javascript
    sort: function() {
        this._grid._sortData();
        this._grid.refresh();
        return $.Deferred().resolve().promise();
    }
```

The loading by page strategy has another implementation:

```javascript
    sort: function() {
        return this._grid.loadData();
    }
```

All you need to do is to redefine loading by page strategy behavior (of course, it's possible to create your own loading strategy but it's more complicated than just override `sort` method):

```javascript
    jsGrid.loadStrategies.PageLoadingStrategy.prototype.sort = function() {
        this._grid._sortData();
        this._grid.refresh();
        return $.Deferred().resolve().promise();
    }
```

**Comment by shandy05** [comment]
thanks for solution :)
