### ISSUE TITLE
Error: b.sortingFunc is not a function

### ISSUE THREAD

**Issue by stephenlawuk** [tabalinas/jsgrid#311]
I have a grid with only two select columns and it works for getting data and filtering but I'm getting an error in jsgrid.min.js (line 7, col 11960) when I click to sort either of the select column headers. 

```
TypeError: b.sortingFunc is not a function
...&this.data.sort(function(c,d){return a*b.sortingFunc(c[b.name],d[b.name])})},_so...
```

**Comment by tabalinas** [comment]
Could you provide a jsfiddle demonstrating the issue (e.g. fork from this one https://jsfiddle.net/stmo5mtf/)?
Or at least provide your grid config.

**Comment by stephenlawuk** [comment]
https://jsfiddle.net/ytmjhns7/1/

I think I possibly know what is causing it now I put that fiddle together using local data rather than my AJAX requests. At the start of my select values I put in a blank objects for the selects to use so that they are not selected by default. 
`{"AssessmentName": "", "IDUnit": "" }`
and 
`{ "CriteriaCode": "", "IDUnit":""}`

If you take those away the sorting works but with them in the sorting breaks. I'm guessing it doesn't like the fact that the database is sending more than just the textfield and valuefield data even though it is not used in the select.

**Comment by tabalinas** [comment]
For the first issue: the reason is that `select` field tries to understand the type of field (numeric or string) of the `valueField` to pick up right sorter etc. And since the first item has not `valueField` it picks up non-existing sorter and fails afterward. It's a bug, that's going to be fixed.

For the second question: yes by default it sorts by ids for the select field, but you can easily provide your sorter, like the following for your case:

```js
sorter: function(id1, id2) { 
                    var item1 = $.grep(x, function(i) { return i.IDAssessment === id1 })[0];
                    var item2 = $.grep(x, function(i) { return i.IDAssessment === id2 })[0];
                    return item1.AssessmentName.localeCompare(item2.AssessmentName);
           }
```

https://jsfiddle.net/tabalinas/ytmjhns7/3/
