### ISSUE TITLE
Custom sorting strategies: sorting function receiving values instead of indexes

### ISSUE THREAD

**Issue by zopyx** [tabalinas/jsgrid#346]
I have a column 'size' containing values like '10 MB', '20 KB' etc. for file sizes.

I configured a custom sorter 

     { name: "size", title: "Size", type: "text", width: 40, css: 'field-size', filtering: false, sorter: 'filesize'},

      jsGrid.sortStrategies.filesize = function(index1, index2) {
            console.log(index1, index2);
     };

On the console I see the values as stated above instead of the index numbers of the related rows...implementation error or documentation error?

Using jsgrid 1.4.1.

**Comment by tabalinas** [comment]
No, the docs is correct, but maybe this is a bit not clear http://js-grid.com/docs/#custom-sorting-strategy.
You can see that the config of the field has `Index` field, and this field is provided in the clients data. That's why it can be used as the index. In fact this is field value that is provided to the sort strategy.

But I agree it's a bit misleadingly written in the docs. I'll try to improve it.
