### ISSUE TITLE
Custom field with anguler ng-click event

### ISSUE THREAD

**Issue by VladislavBI** [tabalinas/jsgrid#347]
I put my jsgrid inside of angular controller to share data between them. I create one custom field with ng-click directive from this controller. But this directive fires only when page loades, and this field even not shown at my page
Field annuonce:
```js
var MyDateField = function (config) {
                jsGrid.Field.call(this, config);
            };

            MyDateField.prototype = new jsGrid.Field({
                sorter: function (date1, date2) {
                    return new Date(date1) - new Date(date2);
                },

                itemTemplate: function (value, obj) {
                    if (value) {
                        //Link to new reporst popUP
                        return "<a  class='btn btn-default' onclick='ctrl.openCreateParamPopUp()'>" + value.length + "</a>";
                    }
                }
            });`
```
field using:

```js
{ name: "Param", type: "myDateField", width: 30 },
```

**Comment by tabalinas** [comment]
The reason is angular doesn't compile your html. So you need to compile it manually.
Inject `$compile` and return from your `itemTemplate` the following:

```js
itemTemplate: function (value, obj) {
    return $compile("<a  class='btn btn-default' onclick='ctrl.openCreateParamPopUp()'>" + value.length + "</a>")($scope);
}
```

This should work.
I'm currently working on integration of jsgrid with angular (here is the project https://github.com/tabalinas/ng-jsgrid).
It's close to be ready and soon will be published. But already now you can find some inspiration on how to use it with angular from demos (see `demo` dir).
This compilation, mentioned above, will be transparent with `ngjsgrid`.

**Comment by VladislavBI** [comment]
It worked as for me, thanks)

**Comment by tabalinas** [comment]
You are welcome!
