### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by fredericoregateiro** [tabalinas/jsgrid#357]
Is there an option to use operations, insert and update, in batch mode?

Thanks

**Comment by tabalinas** [comment]
- What do you mean by batch insertion? Having several insert rows at once? 
 - And for the update, it means being able to edit several rows at once? 
 - One more question: do you expect batch editing with UI or though API?

**Comment by fredericoregateiro** [comment]
Hello,
By batch update i mean the end user can insert, update and delete several rows and send then send all those operations in the same ajax call.
Something like this: http://demos.devexpress.com/MVCxGridViewDemos/Editing/BatchEditing

**Comment by tabalinas** [comment]
For the batch delete checkout the demo *Batch Delete* http://js-grid.com/demos/
The same principle can be applied for inserted and edited data. Just in the controller `updateItem` and `insertItem` methods instead of sending data to the server save data on the client-side. And send all changed data when user is ready.
