### ISSUE TITLE
onItemEditing cancelled

### ISSUE THREAD

**Issue by hxishan** [tabalinas/jsgrid#368]
hi,

is there any callback function that is called when the cancel button is clicked on a row that is being edited?

**Comment by tabalinas** [comment]
There is no such callback to handle edit cancel. 
A couple of options come to mind:
 - reload `_createCancelEditButton` of the control field and attach a handler to cancel button
```js
  {
    type: "control"
    _createCancelEditButton: function() {
      var $result = jsGrid.fields.control.prototype._createCancelEditButton.apply(this, arguments);
      $result.on("click", function() { /* your handler here */ });
      return $result;
    }
  }
```
 - reload `cancelEdit` method of the jsGrid (in the similar way as for the control field above)

Would be interesting to hear about your use case.

**Comment by hxishan** [comment]
thanks a lot @tabalinas 
using the jsgrid onItemEditing to set a couple of dropdowns and then need to reset those on cancelEdit

**Comment by SamuelMS** [comment]
@tabalinas This would actually be pretty useful for my use case too. I'm building an inline detail view for when a user edits a row; basically, I append a new row to the table under the selected row that displays additional information for a given property (database relations, for instance).

I'm hooking into the `onItemEditing` callback to trigger the detail view display, and I can hook into `onItemUpdated` to hide the detail view on save. However, since there is no `onItemEditCancel` or equivalent callback, it's much less convenient to detect when the user closes the edit box (without saving).

I'd be happy to submit a PR for the cancel event if this is a use case you'd like to support.

**Comment by tabalinas** [comment]
@SamuelMS, sounds good to me. PR would be highly appreciated. Thank you!

**Comment by tabalinas** [comment]
@SamuelMS, thank you very much for the efforts! Asked for a little change in the comments to the PR.

No particular reason for `grunt-contrib-qunit` version, feel free to update it.

**Comment by SamuelMS** [comment]
@tabalinas Done and done.

**Comment by tabalinas** [comment]
@SamuelMS, perfect, thank you!

**Comment by davehayes** [comment]
At the moment I can't wait for 1.6, npm has 1.5.3. Meanwhile I've had to do this (for those of you getting here via google). 

```javascript
jsGridConfig.onItemEditing = function(args) {
  window.setTimeout(function() {
      $('.jsgrid-cancel-edit-button').one('click.avoidAuthorClickHandler', function() {
          ...your code here...
          return true;
      });
   }, 200);
};
...
$('#mygrid').jsGrid(jsGridConfig); 
// jsGridConfig is not some special jsGrid thing, it's just the name of my config object
```
I realize this is a horrible kludge, but it works mostly. The timing may be an issue.
