### ISSUE TITLE
How to Load/ Retrieve the Saved date into jsGrid 

### ISSUE THREAD

**Issue by PssNsk** [tabalinas/jsgrid#376]
I am using Spring mvc flow.  i have retrieve data from database to controller, what my problem is , i cant load that data into JSGrid..How can I load this?

**Comment by tabalinas** [comment]
Not sure it's feasible to help w/o additional info.
What is the problem you have with loading data?
What is the configuration of jsgrid?
What is the format of data returned by controller? Is it a REST-ful service?

**Comment by PssNsk** [comment]
Controller
-----------
[controller.txt](https://github.com/tabalinas/jsgrid/files/385690/controller.txt)
[jquery.txt](https://github.com/tabalinas/jsgrid/files/385691/jquery.txt)



html
-----

jquery
--------

**Comment by tabalinas** [comment]
The client-side has several issues. Among them: setting up grid options even before it's created, loading grid after rendering (use `autobind: true` config option instead), setting `data` option (it's used only for static data).

Checkout the `OData Service` demo for the client-side part http://js-grid.com/demos/
Just instead of OData service endpoint use your java REST-script.

It's planned to provide also sample with a Spring backend. I'll update you on this.
