### ISSUE TITLE
filterTemplate js console error

### ISSUE THREAD

**Issue by ecropolis** [tabalinas/jsgrid#377]
I created a jsFiddle to show the problem https://jsfiddle.net/ecropolis/whcmzr5q/2/ 
on my app I'm loading the data via ajax and that breaks so my grid does not get populated. I'm not sure if it is a bug or if I'm doing something wrong but it seems like the UI is rendering how I expect. I haven't finished the functionality here but my plan is to execute a new ajax/query and return a new result so I really want the filter done on the server side for the status column. (This fiddle has the error but when the data is static rather than loaded via ajax, the data still loads. https://jsfiddle.net/ecropolis/whcmzr5q/)

![image](https://cloud.githubusercontent.com/assets/5625387/17147861/379b1648-532a-11e6-8457-581d10919250.png)

**Comment by tabalinas** [comment]
The reason is that when you redefine `filterTemplate` you either should redefine `filterValue`, or if you want to keep existing implementation, you need to save `this.filterControl` variable (grid just cannot predict what you have you the filterTemplate to get value from it).

So if you prefect second option the fix will be:

```js
filterTemplate:function(){
	console.log(this);
	var $result = this.filterControl = $('<select><option value="1">Confirmed</option><option value="0">Non-Conf</option><option value="8">Not-In</option></select>').on("change", function(o,v) {
		console.log(v);
		console.log(o);
	});
	return $result;
}
```
