### ISSUE TITLE
Deleting rows from table

### ISSUE THREAD

**Issue by psumstr** [tabalinas/jsgrid#4]
Hi,

Congrats on an excellent project. I've started to use it, but I've hit a roadblock. For some reason, I can't get a row to be deleted from the table. I'm passing the item to be deleted, but nothing seems to happen. For example:

$(element).jsGrid("deleteItem", {"Host Name": "seattle"});

Any ideas of what might be going on, or any examples that you can link to?

**Comment by tabalinas** [comment]
Hi,

Thank you!
According to docs for `deleteItem`, it accepts item|$row|rowNode is the reference to the item or the row jQueryElement or the row DomNode. Since js literal object `{}` is a new object, so the item just cannot be found in the grid data.

To make it work you can use a reference to item:

`$(element).jsGrid("deleteItem", data[0]); // delete first item`

Docs link: http://js-grid.com/docs/#deleteitemitemrowrownode-promise

**Comment by psumstr** [comment]
Tabalinas, I figured out the problem. I was using the data option and not the controller option to load my data. As soon as I changed it to use  loadData function, everything worked.

Thanks

**Comment by psumstr** [comment]
One more question, is there a way to batch delete?

**Comment by tabalinas** [comment]
If you mean batch delete with UI, it can be done with custom field to select several items.
See following fiddle http://jsfiddle.net/tabalinas/40atrzbo/
Hope it's what you mentioned.

**Comment by tabalinas** [comment]
Fixed

**Comment by wonsuc** [comment]
@tabalinas I need a help.
I'm trying to implement batch delete with UI based on your fiddle source code.
And I get this error on my console.
<img width="522" alt="2018-02-08 4 09 44" src="https://user-images.githubusercontent.com/9866158/35936242-03ee5b04-0c86-11e8-84dc-3d79423251c0.png">
I needed callback listener when all file deleted. So I added callback function when file deleted as below.
```
$("#jsgrid").jsGrid("deleteItem", item).done(function() {
    console.log("Delete completed.");
});
```
It works well, but if the jsGrid instance has pages, the error keep occurring at the every last child of all pages except first page, and it only happens if you selected multiple rows, but a single row.
It seems it's a bug. Should I use 'try catch' when I run batch delete with UI? (Since this issue is not that critical)
I will be thankful with any comment!

**Comment by wonsuc** [comment]
Sorry I fixed by myself.
It is happening because of `loadStrategy` and every time when I delete some row the page is go back first page, so when the code try to delete second row, the row is not exists at current view anymore.
This answer helped me a lot => https://github.com/tabalinas/jsgrid/issues/43

```
jsGrid.loadStrategies.DirectLoadingStrategy.prototype.finishDelete = function(deletedItem, deletedItemIndex) {
    var grid = this._grid;
    console.debug(grid);
    grid.option("data").splice(deletedItemIndex, 1);
    grid.refresh();
    if (grid.option("data").length == 0) {
        grid.reset();
    } else if (grid._content[0].children.length == 0) {
        var targetPageIndex = grid.pageIndex == 1 ? 1 : grid.pageIndex - 1;
        grid.openPage(targetPageIndex);
    }
}
```

**Comment by tabalinas** [comment]
@wonsuc, glad that you figured it out.
