### ISSUE TITLE
how to format a date field?

### ISSUE THREAD

**Issue by comiscienceknight** [tabalinas/jsgrid#437]
from a C# datetime value to jsgrid field value, format of date is like : 2016-09-15T11:34:33.6567475+02:00
how can i set date field format ?

**Comment by tabalinas** [comment]
Important point: js-grid doesn't have date field. It's just an example in docs. 
Since this date field is your custom field, you are free to do formatting yourself. Search for the answer how to set C# datetime to jQuery datepicker, e.g. this one http://stackoverflow.com/questions/24184073/working-with-datetime-date-picker

**Comment by comiscienceknight** [comment]
@tabalinas  thanks a lot.

**Comment by ahmadzahabi1** [comment]
insertTemplate: function (value) {
                    return this._insertPicker = $("<input>").datepicker({defaultDate: new Date(),dateFormat: "yy-mm-dd"});

                },

                editTemplate: function (value) {
                    return this._editPicker = $("<input>").datepicker({ dateFormat: "yy-mm-dd" }).datepicker("setDate", new Date(value));

                },
