### ISSUE TITLE
How add new image icon in grid control column 

### ISSUE THREAD

**Issue by sri596** [tabalinas/jsgrid#472]
Apart from edit & delete icons, i want to add my customized icon in grid control column. I want to write my custom action If this icon is clicked.

Can you please provide simple example? 

Thanks

**Comment by tonisostrat** [comment]
You need to override the various templating functions in `[control](https://github.com/tabalinas/jsgrid/blob/master/src/fields/jsgrid.field.control.js)` and append your own buttons to the default ones, i.e.

```
itemTemplate: function(value, item) {
    var buttons = this.__proto__.itemTemplate.call(this, value, item);

    //add whatever you want here

    return buttons;
},
```

**Comment by sri596** [comment]
Appreciate if you can provide sample examples/links.

**Comment by tabalinas** [comment]
@sri596, not sure what you are expecting from examples, but it's quite straightforward based on the @tonisostrat 's snippet:

```js
itemTemplate: function(value, item) {
    var $result = this.__proto__.itemTemplate.call(this, value, item); //the default buttons

    var $myButton = $("<button>").click(function() { console.log('my button clicked') });

    return $result.add($myButton);
},
```

PS: probably better would be to use `Object.getPrototypeOf` instead of `__proto__`, find more info  [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf).
