### ISSUE TITLE
add class input default

### ISSUE THREAD

**Issue by mautrung09** [tabalinas/jsgrid#476]
I think you should add a default class for input on the input grid = name in the database, when the operation is to add or milk, it would help him manipulate a lot from javascript

**Comment by tonisostrat** [comment]
But how would you differentiate between an **insert**, **edit** or **filter** input? It's possible to add the type of input in the class name but that just creates more mess on the DOM level. Also, what happens when you have a column where the insert cell has multiple inputs or more complex logic? Where would you put the class name?

Alternatively, you can just use already-existing functionality.

```javascript
// you have multiple ways to get the Field object, bear with me.

var field = $('[selector]').jsGrid('option', 'fields').filter(function (field) {
  return field.name == '[fieldName]'
})[0];

// OR

var field = $('[selector]').data('JSGrid')._normalizeField('[fieldName]');

// Now that you have the Field itself you can access all of its elements

field.insertControl // insert cell content as jQuery element
field.editControl // edit cell content as jQuery element
field.filterControl // edit cell content as jQuery element
```

**Comment by tabalinas** [comment]
@mautrung09, this could bring an unexpected behavior, since field name could be quite weird.
Indeed, it's possible to follow the way @tonisostrat proposed.

Or if you know the index of the field the input can be retrieved like this
```js
$(".jsgrid-insert-row").children().eq([field index]).find("input")
```
