### ISSUE TITLE
If you don´t define  {type: "control"}, a weird bug occurs

### ISSUE THREAD

**Issue by rui-ribeiro** [tabalinas/jsgrid#499]
Hi!

Take in mind this case scenario: 

When you want a table without actions.
You just don´t include: {type: "control"} on field columns.

But when you do that, that occurs.

![image](https://cloud.githubusercontent.com/assets/10476926/19810871/febd37f6-9d26-11e6-8030-1b9c4694ea83.png)

**Note:** If you set inserting to false, the problem is gone.

Thanks for your work!

**Comment by tonisostrat** [comment]
That's not a bug, it's by design. If you don't enable/include the control column you don't have any way to toggle the insert/filter rows so they're always visible.

**Comment by rui-ribeiro** [comment]
Ah! I see.

So I have to catch the key event on enter key?

Because enter doesn't trigger submit, right?

**Comment by tonisostrat** [comment]
Filtering (gray row) will work on Enter keypress but you will need to implement the buttons for inserting (green row) *or* add the Enter keypress listener to all the input fields.

**Comment by tabalinas** [comment]
Indeed, this is by design. In fact `filtering: true` turns on filtering row, `inserting: true` turns on insertion row. When you have control button it allows to switch between both modes, so you see only one row (filtering or insertion).
But if control field is not there, this means it's up to you to implement the expected behavior.
As for the `Enter` key: you could have an external insertion button or handle keypress on all or a particular field only, all up to you.
