### ISSUE TITLE
Highlight Row after edit

### ISSUE THREAD

**Issue by sukothap** [tabalinas/jsgrid#518]
Is there a way for me to highlight a row or change the color of the row background (Ex. set to yellow) once I've finished editing the row?

**Comment by tabalinas** [comment]
Use `onItemUpdated` callback (http://js-grid.com/docs/#onitemupdated), in args of the callback you cn get a `row` and add a css class to the row.

**Comment by sukothap** [comment]
I've got the highlight working, but the class name doesn't seem to stick if I were to move on to other pages on the grid and come back. It only applies to the current page. Is there a way to overcome that?

**Comment by tabalinas** [comment]
Yes, since grid data is refreshed, it doesn't know anything about your css class.
To keep the highlight after refresh you could do the following: 
1. on `onItemUpdated` in `args.item` set some field, e.g. `item.isNew = true` (you can also do it on backend side).
2. set in the config `rowClass: function(item) { return item.isNew ? 'is-new' : ''; }`

**Comment by ahmadzahabi1** [comment]
```
rowClass: function(item, itemIndex) {
                    return itemIndex%2==0 ? 'bg-red' : 'bg-green';
                },
```

.bg-red td {
    background-color: #f08080 !important;
}
.bg-green td{
    background-color: #90ee90 !important;
}
