### ISSUE TITLE
How to stop deleteItem event

### ISSUE THREAD

**Issue by randall84** [tabalinas/jsgrid#54]
How can i stop the deleteItem events when occurs an error at server side?

      deleteItem: function (item) {
         alert("inizio");
         $.ajax({
            type: "POST",
            url: "http://localhost/jsGrid.aspx/DeletePdv",
            contentType: "application/json; charset=utf-8",
            data: '{ id:' + item.id + '}'            
         });
      }

thanks

**Comment by tabalinas** [comment]
What is about option `deleteConfirm` http://js-grid.com/docs/#deleteconfirm-default-are-you-sure
If `confirmDeleting` is `true`, then `deleteConfirm` function is executed and should return `false` to prevent deletion.

**Comment by randall84** [comment]
i know it, but it is client side
I need to verify if the delete was successful

**Comment by tabalinas** [comment]
If you loading data by pages (`pageLoading=true`), you have to do nothing, because grid on delete just reloads current page.
For direct loading you have to change `finishDelete` method. Read this issue for more details: https://github.com/tabalinas/jsgrid/issues/43

You could redefine `finishDelete` like following:

```javascript
jsGrid.loadStrategies.DirectLoadingStrategy.prototype.finishDelete = function(deletedItem, deletedItemIndex) {
    if(deletionFailed) { // define deletionFailed on done of delete ajax request in deleteItem of controller
        return;
    }

    var grid = this._grid;
    grid.option("data").splice(deletedItemIndex, 1);
    grid.refresh();
};
```
