### ISSUE TITLE
Bootstrap or Theme Paging

### ISSUE THREAD

**Issue by 19peaches** [tabalinas/jsgrid#551]
I've read through all the docs, but I'm not understanding how to change the paging to use bootstrap paging. We have all these options for paging, but none of them really explain how to do custom styling for your paging.

```
pagerContainer: null,
pageIndex: 1,
pageSize: 20,
pageButtonCount: 15,
pagerFormat: "Pages: {first} {prev} {pages} {next} {last} &nbsp;&nbsp; {pageIndex} of {pageCount}",
pagePrevText: "Prev",
pageNextText: "Next",
pageFirstText: "First",
pageLastText: "Last",
pageNavigatorNextText: "...",
pageNavigatorPrevText: "...",
pagerRenderer: null
```

Can somebody please give me a hand with this or point me in the right direction?

Thanks.

**Comment by tabalinas** [comment]
You can look at css classes attached to every pager element and customize styles for this classes.

Here are the classes definitions:

```js
        pagerContainerClass: "jsgrid-pager-container",
        pagerClass: "jsgrid-pager",
        pagerNavButtonClass: "jsgrid-pager-nav-button",
        pagerNavButtonInactiveClass: "jsgrid-pager-nav-inactive-button",
        pageClass: "jsgrid-pager-page",
        currentPageClass: "jsgrid-pager-current-page",
```

**Comment by RenanLazarotto** [comment]
I know this issue is quite old, but since I ran across it and decided to try to fix it myself, I thought it would be nice to share here. I overwrote the classes tabalinas said with Bootstrap's pagination attributes and managed to get it working as I wanted. Everything is in [this gist](https://gist.github.com/RenanLazarotto/1b14b99823971c15d2efb59a597e3a81). The final result is [here](https://i.ibb.co/WkPZLdP/jsgrid-pagination.png). The blueish, top pagination is from jsGrid and the purpleish I've added just for comparision (the different color comes from the template I'm using).
