### ISSUE TITLE
Official Date field in jsGrid

### ISSUE THREAD

**Issue by BZinser** [tabalinas/jsgrid#561]
I'd like to request jsGrid to have an official field for Dates, much like the one you supply as an example of a Custom Field. 

However, if it were implemented, I would recommend implementing it from the TextField instead of the base Field, as there is more functionality tacked onto the Field at that point.

Thank you!

**Comment by tabalinas** [comment]
Full-featured datepicker probably even more complex than a grid itself. 
So creating it as a built-in feature is not an option. 
Using jQuery UI datepicker would couple js-grid to jQuery UI library. Currently, it's not the case. 
That's why I decided to provide just a code sample, so you can use any other data picker (there are plenty of them) if needed.
