### ISSUE TITLE
SelectedIndex don't work 

### ISSUE THREAD

**Issue by pedrotvr** [tabalinas/jsgrid#569]
Hello,

I'm using your grid in my app, it's a fine grid but i have a problem in a select field, i have tried  to start field with selectIndex diferent and he accepts that value, but this line of code on _createSelect, does nothing:

$option.prop("selected", (selectedIndex === index));

Can anyone help me with a solution ? i don't want to make val() to set a default value after rendering the object...

Thank you,

Pedro Fernandes.

**Comment by tabalinas** [comment]
Not sure what you mean by "does nothing". If you are talking about editing row, then it's expected behavior, since the selected value is defined by item field value.
So it really makes sense for inserting row and filter row.
If you are talking about problem in inserting or filter row, then could you provide an example in jsfiddle or probably a page with public access demonstrating the issue?

**Comment by pedrotvr** [comment]
No it's a problem editing row, i save in storage the selectedIndex and when i refresh page i mantain all changed data in rows...

I will try to find another solution, thank you :)

**Comment by tabalinas** [comment]
To have expected behavior depending on `items` of the select field you need to do the following:
1. if `items` is an array of objects, you have to save to storage the `valueField` field. For example having `items: [{ id: 100, name: "value1" }, ...]` and `valueField: "id"` you need to save `"100"`.

2. if `items` is an array of primitives, you have to save the index of the value. For example having `items: ["value1", "value2", ...]` you need to save "1" for "value2".

`selectedIndex` is used really as a default value for filtering or inserting.
