### ISSUE TITLE
field with array as value

### ISSUE THREAD

**Issue by cleanalot** [tabalinas/jsgrid#581]
I've created a field that handles json-array but I'm having some problems when updating. If I have an array with three values [1,2,3] and remove them all and change it to [4] and hit update it merges the values instead of replacing them so the updated item looks like [1,2,3,4]. I've tracked it down to the $.extend function in _updateRow where the deep-parameter of the function is set to true which makes the merge become recursive. If I remove the true parameter it replaces the array-value completely which I want but then the read-only fields are removed. What I have right now is that I fill the array with null values so that the sizes of original and updated array are the same, e.g. [4,null,null]. This works but doesn't seem like the best solution. Does anyone have any other suggestions?

**Comment by tabalinas** [comment]
Could you please reproduce an example of your use case in jsfiddle (fork this one for instance https://jsfiddle.net/tabalinas/v6ww51ez/)?

**Comment by cleanalot** [comment]
Sure, here:
https://jsfiddle.net/vdqbn1db/

if you change the Array value from 1,2,3 to just 4 it becomes 4,2,3 after update. You can see in the editValue-function of the repeating custom field that I commented out the filling of the array with null values to replace the other values.

**Comment by tabalinas** [comment]
Indeed, there is an issue with arrays, which extended instead with `$.extend(true, ...)` as usual.
We really need deep extending, since nested fields are supported.
I guess, the best would be to store data in field value as `JSON.stringify(value)`. And in `itemTemplate` just parse it with `JSON.parse(value)`.
I'm afraid we don't have better alternatives (please, share if you have any).
