### ISSUE TITLE
Bootstrap grid refresh

### ISSUE THREAD

**Issue by bluenose1970** [tabalinas/jsgrid#589]
I have a js-grid embedded in a Bootstrap accordion.

To format the grid format I call the following:

$('#accordion')
.on('shown.bs.collapse',
      function (e) {
               $('#jsGridMyGrid').jsGrid('refresh');
}

This works fine and the grid resizes correctly but the refresh is visible to the user, is there any way to hide the refresh process so when the user views the grid it is already refreshed and doesn't 'snap' into place?

Thanks.

**Comment by tabalinas** [comment]
If grid would be rendered in a visible container this issue should not happen. Since accordion item is hidden grid cannot be rendered properly.
Regarding the visual effect, it's hard to say not seeing the problem.
Do you have a page with public access to it? or probably you could prepare a jsfiddle to show the problem (forking this one for instance https://jsfiddle.net/tabalinas/v6ww51ez/).

**Comment by tabalinas** [comment]
No answer, closing
