### ISSUE TITLE
editRowRenderer, add control buttons

### ISSUE THREAD

**Issue by tbellembois** [tabalinas/jsgrid#597]
Hi,

I try to build a custom row renderer:
```bash
editRowRenderer: function(item, itemIndex) {
    var fn = $("<input>").attr("type", "text").attr("name", "FirstName").val(item.FirstName);
    var ln = $("<input>").attr("type", "text").attr("name", "LastName").val(item.LastName);
    return $("<tr>").append($("<td>")).append(fn).append(ln);
},
```
But I can't figure out how to add the jsGrid control buttons.
I have tried several thinks such as `.append(new jsGrid.ControlField()` but it does not work.

Thanks for your help.

**Comment by tabalinas** [comment]
Depending on the template it can be:

```js
var $controlButtons = jsGrid.fields.control.prototype.editTemplate.call(this);
// append them to the result
```

**Comment by tbellembois** [comment]
Thanks for the reply.
I have an error in my JS console:
```javascript
Uncaught TypeError: this._createUpdateButton is not a function
    at Grid.editTemplate (jsgrid.js:2396)
    at Grid.editRowRenderer ((index):121)
    at getOrApply (jsgrid.js:30)
    at Grid.renderTemplate (jsgrid.js:224)
    at Grid._createEditRow (jsgrid.js:1257)
    at Grid._editRow (jsgrid.js:1247)
    at Grid.editItem (jsgrid.js:1215)
    at Grid.rowClick (jsgrid.js:88)
    at Grid.<anonymous> (jsgrid.js:619)
    at HTMLTableRowElement.e (jquery-3.1.1.min.js:2)
```

What do you mean by "Depending on the template" ? I have not defined any extra template.

Thanks.

**Comment by tabalinas** [comment]
You are right, the code above is incorrect.
By design custom row renderer assumes custom row content. This means that even if you would put standard control fields, they won't work as expected. Since controls are custom, js-grid fields doens't know anything about them and cannot read their values.

It's demonstrated in the fiddle:
https://jsfiddle.net/tabalinas/gaeL2kr8/

Even though we have control fields rendered, it fails on submitting changes.
This means using custom row renderer requires implementing update/delete logic. Here is the example:

https://jsfiddle.net/tabalinas/koja0mqp/

**Comment by tbellembois** [comment]
Thanks for the example !
It is now clear to me.

**Comment by tabalinas** [comment]
You are welcome!
