### ISSUE TITLE
oData example, slight problem, "Not found"

### ISSUE THREAD

**Issue by Junglefish** [tabalinas/jsgrid#604]
Hi

I am using the standard oData example. However, I keep getting a "Not found" message in the grid in the browser instead of the data.

Here's the code:

```js
$(function() {
 
    $("##jsGrid").jsGrid({
        height: "auto",
        width: "100%",
 
        sorting: true,
        paging: false,
        autoload: true,
 
        controller: {
            loadData: function() {
                var d = $.Deferred();
 
                $.ajax({
                    url: "#event.buildLink("Users.rolesAsJson")#",
                    dataType: "json"
                }).done(function(response) {
                    d.resolve(response.value);
                    console.log(response);
                    console.log(response.value);
                    console.log(d.resolve(response.value));
                });

                return d.promise();
            }
        },

        fields: [
            { name: "role_ky", type: "number" },
            { name: "role_name", type: "text"},
            { name: "ROLE_TEXT", type: "text"},
            { name: "ROLE_RANKING", type: "number"},
            { name: "ROLE_STATUS", type: "number"},
            { name: "ROLE_DATE_CREATED", type: "text"},
            { name: "ROLE_DATE_AMENDED", type: "text"}
         ]
    });
 
});
```

If you look at the three console.log()s they give me this, in order:
An object containing the COLUMNS and DATA (the json result of my query)
undefined
An empty object

So I guess my question is, why is response.value undefined? And what do I do about it?

**Comment by tabalinas** [comment]
This has nothing to do with js-grid itself.
Most probably there is an issue with your OData service.
Check your backend configuration so that you can get data w/o js-grid (open the url in the browser or in Postman).
Ensure there are data in DB (probably there are no data).
Check this post about OData service creation: https://www.codeproject.com/Articles/1033244/OData-Service-using-WCF-Service.
Or at this one OData service + Backbone: https://dzone.com/articles/backbonejs-app-wcf-odata
