### ISSUE TITLE
requirement: select field with non-numeric value property / non-numeric foreign key (FK)

### ISSUE THREAD

**Issue by mansoor-omrani** [tabalinas/jsgrid#618]
When using fields whose type is "select" we can provide an array of items. It seems though the valueField property by which we can customize the value attribute in <option> elements can only point to numeric columns in the datasource.

That said, we are not able to define a foreign key field whose related primary key is non-numeric, like a string. In other words, jsGrid assumes the primary key to be only numeric.

How can we define a "select" field whose values are text (not numeric)?

example:
```js
{
	type: "select",
	valueField: "Id",
	textField: "Name",
	width: 100,
	name: "Color",
	title: "Theme",
	items: [{Id: "red", Name: "Bloody theme"}, {Id: "black", Name: "Dark theme"},{Id: "blue", Name: "Gloomy theme"}]
},
```

**Comment by tabalinas** [comment]
`valueField` of `select` field can be string or numeric. Just define it as you did in the code above.
What kind of issue do you have with it?

**Comment by mansoor-omrani** [comment]
Hi tabalinsa. I used "string" and also "text". But neither did work. When I debugged into jsGrid.js I noticed the 'valueType' of the field is always 'number'. I deem there is some tiny bug in jsGrid. But I cannot figure out what it is.

**Comment by tabalinas** [comment]
It should work. 
What exactly happens when you use string?
What do you mean by "I used "string" and also "text""? Used where?
`valueType` is defined on the fly depending on the type of the `valueField` of the first item (`typeof items[0][valueField]`).

If you think there is a bug, could you reproduce it in a fiddle (or any other page with public access)?

**Comment by mansoor-omrani** [comment]
I know that. valueType is a system property you initialize it on the fly. But it seems this 'valueType' is determined based on the value of the first item in 'Items' array of the given field.

I use an array such as [{ Id: "-", Name: "All"}, {Id: "red", Name: "Red Theme"}, ... ], but the underlying code does not catch the type of 'value' correctly and always thinks it is a 'number' field type. Look at this private function in jsGrid:

```
function SelectField(config) {
        this.items = [];
        this.selectedIndex = -1;
        this.valueField = "";
        this.textField = "";

        if(config.valueField && config.items.length) {
            var firstItemValue = config.items[0][config.valueField];
            **this.valueType = (typeof firstItemValue) === numberValueType ? numberValueType :** stringValueType;
        }

        this.sorter = this.valueType;

        NumberField.call(this, config);
    }
```

**Comment by tabalinas** [comment]
Yes, so since `typeof "-"` gives us `string` code should work as expected.

Could you reproduce the problem in a fiddle (or any other page with public access)?

**Comment by mansoor-omrani** [comment]
Sure. I post the link here after I do it.

**Comment by mansoor-omrani** [comment]
Hi back.

I used one of your own repros and changed it a little.

You can check it out using this link:

[(http://jsfiddle.net/9g8upd33/145/)]

**Comment by richraid21** [comment]
In the given example, the problem is the ID property of the "ALL" listing. The loadData filter is checking to see if Country is present, and it is because of the dash character.

Replace 
`{ Name: "All", Id: "-" },`    
with
`{ Name: "All", Id: "" },`    
and it works fine, if I'm understanding your issue correctly.

**Comment by tabalinas** [comment]
@mansoor-omrani, the problem is not with js-grid but with db filtering function.
Inside `loadData` your code checked:

```js
&& (!filter.Country || client.Country === filter.Country)
```

which is obviously false, since your default country is `"-"`, not an empty string.

So just changing the filtering function fixes the problem:

```
&& (filter.Country === "-" || client.Country === filter.Country)
```

see working fork http://jsfiddle.net/tabalinas/jrc9otky/
