### ISSUE TITLE
on Click of Check box column Row Click event occur 

### ISSUE THREAD

**Issue by yogesh2591** [tabalinas/jsgrid#658]
On Click on Check box  column of row , the row Click event occur . how to differentiate this two event . Editing of grid view is set as false **AND** how to set click on only selected fields. :)

**Comment by richraid21** [comment]
You can do this by adding a class to the field definition, then checking if that class exists before executing the default rowClick behavior. This does of course, require an override of the default rowClick event.

Please see [this codepen](https://codepen.io/richraid21/pen/qrOvMj): The only field that will launch the editor is the "Name" field; the other fields do not because they do not have the css class I defined.

**Comment by yogesh2591** [comment]
@richraid21 thanks for the Solution

**Comment by tabalinas** [comment]
Another solution would be to attach handler to click event of the checkbox and call `event.preventDefault()` so click won't bubble to row.
