### ISSUE TITLE
How to show error messages returned by server beside or under specific field.

### ISSUE THREAD

**Issue by git265** [tabalinas/jsgrid#706]
Hi,

Can someone please help me on how we can show the error messages returned by the server under the respective table cell. Please see below image.(The field is required is error returned by the server and i dont want client side validation) . Currently the client side validators show has alerts instead i want server to validate and show errors for respective field.

![image](https://cloud.githubusercontent.com/assets/4753090/24505141/d7f4a9c4-1526-11e7-83fb-87bd57b0c387.png)

I really appreciate your help.

PS: This plugin is amazing.. Simple and neat.

THanks,

**Comment by richraid21** [comment]
I don't see how this has to do with JsGrid?

**Comment by git265** [comment]
Hi Rich , 

Are you saying this is not related to JSGRID?  Basically below is what i am trying to achieve on update. "Field is required" that is returned from server has to shown below respective row address field. 

![image](https://cloud.githubusercontent.com/assets/4753090/24503713/4a3b700e-1521-11e7-8884-f51aaf91cae0.png)

**Comment by maurorulli** [comment]
@git265 this place is to help about the project JSGRID, not else. Try to ask your questions in technical communities like [stackoverflow](https://stackoverflow.com/)

**Comment by git265** [comment]
I am sorry but i am little confused on why this issue is not related to JSGRID.  JSGRID by default shows the client side error messages in alert window. Instead i want to show below the field.

**Comment by tabalinas** [comment]
@git265, the usual way to change how validate messages outputted is redefining `invalidNotify` function. But it has all the error messages, so it won't work since you need to know the invalid field.
You can try to define `validate` of the field as a `function(value, item)`  (see http://js-grid.com/docs/#field-validation-config), which not only validates the value, but also outputs the validation result as desired. You can find the row using method `rowByItem` of the grid to know where to position your message.
