### ISSUE TITLE
Rows Reordering (Drag and Drop) - demo bug

### ISSUE THREAD

**Issue by maddoxd** [tabalinas/jsgrid#710]
Hello
Firstly, great control thanks!
I have been implementing the drag and drop/reordering functionality as per the demo,
http://js-grid.com/demos/
 but I came across a cosmetic bug - in that if you move the top row, or move a row to the top row, the columns resize.

The same can be seen on the demo too, so I feel it's not anything i'm doing wrong.
Any thoughts? is this a bug in the jquery-ui sortable or the js-grid?
Cheers
maddoxd

**Comment by richraid21** [comment]
Hmm, That's an interesting bug, thanks for pointing it out.

**Comment by tabalinas** [comment]
Yes, this is due to `table-layout: fixed` that is used for the HTML table of the grid:

http://stackoverflow.com/questions/9402789/jquery-ui-sortable-table-resizing-column-when-first-row-is-dragged

Since this an external plugin behavior, I think, we couldn't find any reasonable out-of-box solution to this.
Redefine table-layout as mentioned in SO issue, if this is critical.
