### ISSUE TITLE
Don't want a <input> for text readOnly field

### ISSUE THREAD

**Issue by RevealedFrom** [tabalinas/jsgrid#711]
I have a column of type text and readOnly true.  When in edit mode, I don't want the <input> textbox to show.  I tried this:

`editTemplate: function(value, item) {
                 return value;
              }`

Visually, it works exactly as what I want, ie the existing value is just shown in the table cell.  But now when I try to save an edit, an exception (Cannot read property 'val' of undefined) somewhere in jsgrid.min.js.

I have seen various examples of the editTemplate in issues #682 and #271 but am totally floored by the pattern used.  How do I have simple plain text in edit mode for a text or textarea type, or is there documentation available on how the editTemplate is to be used?

Thanks.

**Comment by tabalinas** [comment]
Once you completely redefines `editTemplate`, the `editValue` should be also redefined. This method should return the edited value of the field. These two properties usually goes along. 

When only `editTemplate` is redefined, once the `editValue` is called it throws because edit control is not created.
