### ISSUE TITLE
jsgrid reload

### ISSUE THREAD

**Issue by PrasadDDharmadhikari** [tabalinas/jsgrid#720]
I used the web service to load the data into jsgrid data coming after button click and on edit click of jsgrid i checked the user is authorized or not. if user not authorised then dont update. it working as expected(value not update into database) but updated value show into the js grid so i want to reload the jg grid. how???

**Comment by jarocks** [comment]
Depending on when you're doing your validation, you would want either your updateItem controller to return the original item or use the onItemUpdating callback to cancel the update ([onitemupdating](http://js-grid.com/docs/#onitemupdating)). With either of those methods the data in the grid wouldn't change so you wouldn't need to reload it.

Otherwise you can just call loadData to reload the grid data in place (without affecting pagination or filters)

**Comment by PrasadDDharmadhikari** [comment]
i call loadData to reload the grid data but filters are lost..

**Comment by tabalinas** [comment]
@PrasadDDharmadhikari, what's about using `onItemUpdating` callback as @jarocks suggested?
http://js-grid.com/docs/#onitemupdating

**Comment by PrasadDDharmadhikari** [comment]
Thanks for reply...I have checked with row arguement but i didnt undersand the who to cancel and show old value.

**Comment by tabalinas** [comment]
You can find an example just below in the section `Cancel Item Update`.

**Comment by PrasadDDharmadhikari** [comment]
args.cancel=true????

**Comment by tabalinas** [comment]
Yes, that's right. 
What is the question?

**Comment by PrasadDDharmadhikari** [comment]
On updateItem controller, i call 2 ajax method 1 is to check the user is authenticated or not. if user have yes then 2nd ajax call and update the row its working fine but if the user is not authenticated then textbox automatically converted into label and show updated value not old value.

**Comment by tabalinas** [comment]
If you do this check on the server side, then your update item request should just fail with `401 unauthorized`. Then update operation won't be completed. The problem now is that you successfully finish the update, so grid thinks it's finished.
