### ISSUE TITLE
How to store checkbox state and checked row CSS state. when loading data using ajax request after every 10 seconds.

### ISSUE THREAD

**Issue by yogesh2591** [tabalinas/jsgrid#723]
Please checked my Codepen sample [here](https://codepen.io/Akki2591/pen/XMLJpZ?editors=0110) .
I am loading data using ajax call after every 10 seconds. when i click on check box ,i change the class of that 
checked row to acknowledge the user that the row is checked  .but when data is reload again after ajax request it does not save the state of check boxes and rows . how to should i perform this task?

**Comment by tabalinas** [comment]
Since you are reloading grid you need to preserve this state somewhere. This could be an array of selected items ids (e.g. `selectedItemIds`).
In grid config you provide `rowClass` that should return necessary selected class for your row (if item's id is in `selectedItemIds`), and define `itemTemplate` of the checkbox field, so that it's checked if the item belongs to `selectedItemIds`.

**Comment by Abhijeet8Sinha** [comment]
@yogesh2591 Hi Yogesh.. Are you able to find the possible solution for the same. 
I am also having a same scenario & unfortunately unable to resolve same. 
Your help will be really appreciated.
