### ISSUE TITLE
[Question] Modify grid data in real time

### ISSUE THREAD

**Issue by 89snake89** [tabalinas/jsgrid#824]
I think could be useful give the possibility to modify fields data, with no rowClick to change in edit mode.
Is there already a implemented solution?

**Comment by tabalinas** [comment]
You can set `data` option (http://js-grid.com/docs/#data) of the grid.
If you want to update a particular item, change it and call `refresh` method (http://js-grid.com/docs/#refresh) to render latest grid data.
If you want to update an item outside of the grid and reflect the changes passing updated through the grid controller (so that backend updates will be triggered) call `updateItem` method of the grid (http://js-grid.com/docs/#updateitemitemrowrownode-editeditem-promise).
