### ISSUE TITLE
Pagination always moving to first page when we click on search icon

### ISSUE THREAD

**Issue by saru19** [tabalinas/jsgrid#843]
Hi,
I am using jsgrid in my project by following demos provided in 
http://js-grid.com/demos/
  In Basic Scenario demo if i go to any other page like suppose 2nd page and click on search icon it is again coming back to first page. But my requirement is it should be on the 2nd page only. Any idea on how to do this ?

**Comment by heiovsky** [comment]
You should be more specific, in what context you want to achieve this, because for example:

Server filtering and paging
table with 1000 records,
gird - 100 record per page -> gives 10 pages
now go to 5th page -> make some filtering that returns let suppose 15 records
so now you are on 5th page when you only have one

I think you dont want this scenario.

**Comment by tabalinas** [comment]
@saru19, scneario @heiovsky described is the exact reason why paging resets on search.
If you don't want to reset on search, redefine `search` method of the grid: https://github.com/tabalinas/jsgrid/blob/master/src/jsgrid.core.js#L1054.
Or redefine search button to call `loadData` method instead of `search`, it doesn't reset paging.

**Comment by saru19** [comment]
Server filtering and paging
table with 1000 records,
gird - 100 record per page -> gives 10 pages
now go to 5th page -> I am not filtering anything just clicking on search icon still it is going to first page.
It should be on the same page(5th)

search: function(filter) {
		             this._resetSorting();
		             this._resetPager();
		             return this.loadData(filter);
		         }

Redefined this function but still it is not working.

**Comment by tabalinas** [comment]
@saru19, do you have a jsfiddle to demonstrate the problem?
