### ISSUE TITLE
How to Remove the delete button from control field after the row is edited once?

### ISSUE THREAD

**Issue by tushardhadiwal** [tabalinas/jsgrid#882]

**Comment by tushardhadiwal** [comment]
Instead of showing custom image, it is also okay, if I can show the newly added rows in different color and updated rows in different color.
also, when I delete a row, it is removed from grid, instead of that, I want it to stay in grid but change the text inside it to striked (text with horizontal line crossing it) text.

**Comment by heiovsky** [comment]
Docs, docs, docs, you are talking about conditional row css. Insted of
delete bind edit to delete action and set property which acts like 'i am
deleted- i want custom css'

21.08.2017 21:18 "Tushar Dhadiwal" <notifications@github.com> napisał(a):

Instead of showing custom image, it is also okay, if I can show the newly
added rows in different color and updated rows in different color.
also, when I delete a row, it is removed from grid, instead of that, I want
it to stay in grid but change the text inside it to striked (text with
horizontal line crossing it) text.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tabalinas/jsgrid/issues/882#issuecomment-323828683>,
or mute
the thread

**Comment by tushardhadiwal** [comment]
@heiovsky Can you explain exactly what needs to be done? I can't find anything elaborately in docs. Thansk,

**Comment by tabalinas** [comment]
> if I can show the newly added rows in different color and updated rows in different color.
@heiovsky is talking about [rowClass](http://js-grid.com/docs/#rowclass). For new item you can set `item.isNew` for edited `item.isEdited` and return row class specific for each condition.

> also, when I delete a row, it is removed from grid, instead of that, I want it to stay in grid but change the text inside it to striked (text with horizontal line crossing it) text.

in this case you will have to define [custom load strategy](http://js-grid.com/docs/#custom-loadstrategy), which won't remove item from `data` collection but just mark it as `item.isDeleted`. `rowClass` will help with setting strikethrough font.
