### ISSUE TITLE
Batch select and filtering

### ISSUE THREAD

**Issue by Ramy54** [tabalinas/jsgrid#92]
Hi,

Thank you for the great work! I am using Js-grid for my tables and it works good.
However I a have this issue I couldn't resolve.
I have implemented a select checkbox column (like in Batch Delete in your demo) but in my case I am not deleting but generating a file from the selected elements.
Anyway, I also use the filtering feature, but every time I filter my table, I lose my selected items.

Do you have a solution I might have missed for that?

Thank you very much!

**Comment by tabalinas** [comment]
Thank you for the feedback!

Since filtering rerenders all the rows you have to take care about these checkBoxes state. Keep track the selected items in an array. And after filtering restore the states. You can restore the state in `itemTemplate` checking whether item is in seleted array. Or you could handle selecting with `onRefreshed` callback: iterate over the rows and set the state of checkboxes.
